# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Xilinx/Zybo-Z7-Master.xdc

# Block Designs: bd/Zynq_Design/Zynq_Design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_Design || ORIG_REF_NAME==Zynq_Design} -quiet] -quiet

# IP: bd/Zynq_Design/ip/Zynq_Design_processing_system7_0_0/Zynq_Design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_Design_processing_system7_0_0 || ORIG_REF_NAME==Zynq_Design_processing_system7_0_0} -quiet] -quiet

# IP: bd/Zynq_Design/ip/Zynq_Design_ps7_0_axi_periph_0/Zynq_Design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_Design_ps7_0_axi_periph_0 || ORIG_REF_NAME==Zynq_Design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Zynq_Design/ip/Zynq_Design_rst_ps7_0_50M_0/Zynq_Design_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_Design_rst_ps7_0_50M_0 || ORIG_REF_NAME==Zynq_Design_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/Zynq_Design/ip/Zynq_Design_AXI4_Lite_Slave_0_0/Zynq_Design_AXI4_Lite_Slave_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_Design_AXI4_Lite_Slave_0_0 || ORIG_REF_NAME==Zynq_Design_AXI4_Lite_Slave_0_0} -quiet] -quiet

# IP: bd/Zynq_Design/ip/Zynq_Design_Local_Bus_Register_B_0_0/Zynq_Design_Local_Bus_Register_B_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_Design_Local_Bus_Register_B_0_0 || ORIG_REF_NAME==Zynq_Design_Local_Bus_Register_B_0_0} -quiet] -quiet

# IP: bd/Zynq_Design/ip/Zynq_Design_xlslice_0_0/Zynq_Design_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_Design_xlslice_0_0 || ORIG_REF_NAME==Zynq_Design_xlslice_0_0} -quiet] -quiet

# IP: bd/Zynq_Design/ip/Zynq_Design_UART_V1_9_0_0/Zynq_Design_UART_V1_9_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_Design_UART_V1_9_0_0 || ORIG_REF_NAME==Zynq_Design_UART_V1_9_0_0} -quiet] -quiet

# IP: bd/Zynq_Design/ip/Zynq_Design_xlslice_0_1/Zynq_Design_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_Design_xlslice_0_1 || ORIG_REF_NAME==Zynq_Design_xlslice_0_1} -quiet] -quiet

# IP: bd/Zynq_Design/ip/Zynq_Design_xlslice_0_2/Zynq_Design_xlslice_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_Design_xlslice_0_2 || ORIG_REF_NAME==Zynq_Design_xlslice_0_2} -quiet] -quiet

# IP: bd/Zynq_Design/ip/Zynq_Design_xlslice_1_0/Zynq_Design_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_Design_xlslice_1_0 || ORIG_REF_NAME==Zynq_Design_xlslice_1_0} -quiet] -quiet

# IP: bd/Zynq_Design/ip/Zynq_Design_xlslice_2_0/Zynq_Design_xlslice_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_Design_xlslice_2_0 || ORIG_REF_NAME==Zynq_Design_xlslice_2_0} -quiet] -quiet

# IP: bd/Zynq_Design/ip/Zynq_Design_AXI_UART_Control_Ada_0_0/Zynq_Design_AXI_UART_Control_Ada_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_Design_AXI_UART_Control_Ada_0_0 || ORIG_REF_NAME==Zynq_Design_AXI_UART_Control_Ada_0_0} -quiet] -quiet

# IP: bd/Zynq_Design/ip/Zynq_Design_system_ila_0_0/Zynq_Design_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_Design_system_ila_0_0 || ORIG_REF_NAME==Zynq_Design_system_ila_0_0} -quiet] -quiet

# IP: bd/Zynq_Design/ip/Zynq_Design_xlconcat_0_0/Zynq_Design_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_Design_xlconcat_0_0 || ORIG_REF_NAME==Zynq_Design_xlconcat_0_0} -quiet] -quiet

# IP: bd/Zynq_Design/ip/Zynq_Design_xbar_0/Zynq_Design_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_Design_xbar_0 || ORIG_REF_NAME==Zynq_Design_xbar_0} -quiet] -quiet

# IP: bd/Zynq_Design/ip/Zynq_Design_auto_pc_0/Zynq_Design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_Design_auto_pc_0 || ORIG_REF_NAME==Zynq_Design_auto_pc_0} -quiet] -quiet

# XDC: bd/Zynq_Design/Zynq_Design_ooc.xdc
