# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir G:/Xilinx/Projects/Desktop/ZyboBaseProject/ZyboBaseProject.cache/wt [current_project]
set_property parent.project_path G:/Xilinx/Projects/Desktop/ZyboBaseProject/ZyboBaseProject.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo-z7-20:part0:1.0 [current_project]
set_property ip_repo_paths g:/Xilinx/IP [current_project]
update_ip_catalog
set_property ip_output_repo g:/Xilinx/Projects/Desktop/ZyboBaseProject/ZyboBaseProject.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files G:/Xilinx/Projects/Desktop/ZyboBaseProject/ZyboBaseProject.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_axi_traffic_gen_mask_0_0.coe
add_files G:/Xilinx/Projects/Desktop/ZyboBaseProject/ZyboBaseProject.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_axi_traffic_gen_control_0_0.coe
add_files G:/Xilinx/Projects/Desktop/ZyboBaseProject/ZyboBaseProject.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_axi_traffic_gen_data_0_0.coe
add_files G:/Xilinx/Projects/Desktop/ZyboBaseProject/ZyboBaseProject.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_axi_traffic_gen_addr_0_0.coe
read_vhdl -library xil_defaultlib G:/Xilinx/Projects/Desktop/ZyboBaseProject/ZyboBaseProject.srcs/sources_1/bd/Zynq_Design/hdl/Zynq_Design_wrapper.vhd
add_files G:/Xilinx/Projects/Desktop/ZyboBaseProject/ZyboBaseProject.srcs/sources_1/bd/Zynq_Design/Zynq_Design.bd
set_property used_in_implementation false [get_files -all g:/Xilinx/Projects/Desktop/ZyboBaseProject/ZyboBaseProject.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_processing_system7_0_0/Zynq_Design_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all g:/Xilinx/Projects/Desktop/ZyboBaseProject/ZyboBaseProject.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_rst_ps7_0_50M_0/Zynq_Design_rst_ps7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all g:/Xilinx/Projects/Desktop/ZyboBaseProject/ZyboBaseProject.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_rst_ps7_0_50M_0/Zynq_Design_rst_ps7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all g:/Xilinx/Projects/Desktop/ZyboBaseProject/ZyboBaseProject.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_UART_V1_9_0_0/src/Arty-A7-Master.xdc]
set_property used_in_implementation false [get_files -all g:/Xilinx/Projects/Desktop/ZyboBaseProject/ZyboBaseProject.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_UART_V1_9_0_0/src/TOP_BD_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Xilinx/Projects/Desktop/ZyboBaseProject/ZyboBaseProject.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_UART_V1_9_0_0/src/TOP_BD_fifo_generator_0_0/TOP_BD_fifo_generator_0_0.xdc]
set_property used_in_implementation false [get_files -all g:/Xilinx/Projects/Desktop/ZyboBaseProject/ZyboBaseProject.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_UART_V1_9_0_0/src/TOP_BD_fifo_generator_0_0/TOP_BD_fifo_generator_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/Xilinx/Projects/Desktop/ZyboBaseProject/ZyboBaseProject.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_UART_V1_9_0_0/src/TOP_BD_fifo_generator_0_1/TOP_BD_fifo_generator_0_1.xdc]
set_property used_in_implementation false [get_files -all g:/Xilinx/Projects/Desktop/ZyboBaseProject/ZyboBaseProject.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_UART_V1_9_0_0/src/TOP_BD_fifo_generator_0_1/TOP_BD_fifo_generator_0_1_clocks.xdc]
set_property used_in_synthesis false [get_files -all g:/Xilinx/Projects/Desktop/ZyboBaseProject/ZyboBaseProject.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all g:/Xilinx/Projects/Desktop/ZyboBaseProject/ZyboBaseProject.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all g:/Xilinx/Projects/Desktop/ZyboBaseProject/ZyboBaseProject.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all g:/Xilinx/Projects/Desktop/ZyboBaseProject/ZyboBaseProject.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_system_ila_0_0/bd_0/ip/ip_0/bd_8632_ila_lib_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Xilinx/Projects/Desktop/ZyboBaseProject/ZyboBaseProject.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_system_ila_0_0/bd_0/bd_8632_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/Xilinx/Projects/Desktop/ZyboBaseProject/ZyboBaseProject.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_auto_pc_0/Zynq_Design_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all G:/Xilinx/Projects/Desktop/ZyboBaseProject/ZyboBaseProject.srcs/sources_1/bd/Zynq_Design/Zynq_Design_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc G:/Xilinx/Projects/Desktop/ZyboBaseProject/ZyboBaseProject.srcs/constrs_1/imports/Xilinx/Zybo-Z7-Master.xdc
set_property used_in_implementation false [get_files G:/Xilinx/Projects/Desktop/ZyboBaseProject/ZyboBaseProject.srcs/constrs_1/imports/Xilinx/Zybo-Z7-Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Zynq_Design_wrapper -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Zynq_Design_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Zynq_Design_wrapper_utilization_synth.rpt -pb Zynq_Design_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
