# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: g:/Xilinx/Projects/Desktop/AXI_4_Lite_Slave/AXI_4_Lite_Slave.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_UART_V1_9_0_0/Zynq_Design_UART_V1_9_0_0.xci
# IP: The module: 'Zynq_Design_UART_V1_9_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: g:/Xilinx/Projects/Desktop/AXI_4_Lite_Slave/AXI_4_Lite_Slave.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_UART_V1_9_0_0/src/TOP_BD_fifo_generator_0_0/TOP_BD_fifo_generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TOP_BD_fifo_generator_0_0 || ORIG_REF_NAME==TOP_BD_fifo_generator_0_0} -quiet] -quiet

# IP: g:/Xilinx/Projects/Desktop/AXI_4_Lite_Slave/AXI_4_Lite_Slave.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_UART_V1_9_0_0/src/TOP_BD_fifo_generator_0_1/TOP_BD_fifo_generator_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TOP_BD_fifo_generator_0_1 || ORIG_REF_NAME==TOP_BD_fifo_generator_0_1} -quiet] -quiet

# XDC: g:/Xilinx/Projects/Desktop/AXI_4_Lite_Slave/AXI_4_Lite_Slave.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_UART_V1_9_0_0/src/Arty-A7-Master.xdc
# XDC: The top module name and the constraint reference have the same name: 'Zynq_Design_UART_V1_9_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: g:/Xilinx/Projects/Desktop/AXI_4_Lite_Slave/AXI_4_Lite_Slave.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_UART_V1_9_0_0/src/TOP_BD_ooc.xdc

# XDC: g:/Xilinx/Projects/Desktop/AXI_4_Lite_Slave/AXI_4_Lite_Slave.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_UART_V1_9_0_0/src/TOP_BD_fifo_generator_0_0/TOP_BD_fifo_generator_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TOP_BD_fifo_generator_0_0 || ORIG_REF_NAME==TOP_BD_fifo_generator_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: g:/Xilinx/Projects/Desktop/AXI_4_Lite_Slave/AXI_4_Lite_Slave.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_UART_V1_9_0_0/src/TOP_BD_fifo_generator_0_0/TOP_BD_fifo_generator_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TOP_BD_fifo_generator_0_0 || ORIG_REF_NAME==TOP_BD_fifo_generator_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: g:/Xilinx/Projects/Desktop/AXI_4_Lite_Slave/AXI_4_Lite_Slave.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_UART_V1_9_0_0/src/TOP_BD_fifo_generator_0_1/TOP_BD_fifo_generator_0_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TOP_BD_fifo_generator_0_1 || ORIG_REF_NAME==TOP_BD_fifo_generator_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: g:/Xilinx/Projects/Desktop/AXI_4_Lite_Slave/AXI_4_Lite_Slave.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_UART_V1_9_0_0/src/TOP_BD_fifo_generator_0_1/TOP_BD_fifo_generator_0_1_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TOP_BD_fifo_generator_0_1 || ORIG_REF_NAME==TOP_BD_fifo_generator_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: g:/Xilinx/Projects/Desktop/AXI_4_Lite_Slave/AXI_4_Lite_Slave.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_UART_V1_9_0_0/Zynq_Design_UART_V1_9_0_0.xci
# IP: The module: 'Zynq_Design_UART_V1_9_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: g:/Xilinx/Projects/Desktop/AXI_4_Lite_Slave/AXI_4_Lite_Slave.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_UART_V1_9_0_0/src/TOP_BD_fifo_generator_0_0/TOP_BD_fifo_generator_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TOP_BD_fifo_generator_0_0 || ORIG_REF_NAME==TOP_BD_fifo_generator_0_0} -quiet] -quiet

# IP: g:/Xilinx/Projects/Desktop/AXI_4_Lite_Slave/AXI_4_Lite_Slave.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_UART_V1_9_0_0/src/TOP_BD_fifo_generator_0_1/TOP_BD_fifo_generator_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TOP_BD_fifo_generator_0_1 || ORIG_REF_NAME==TOP_BD_fifo_generator_0_1} -quiet] -quiet

# XDC: g:/Xilinx/Projects/Desktop/AXI_4_Lite_Slave/AXI_4_Lite_Slave.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_UART_V1_9_0_0/src/Arty-A7-Master.xdc
# XDC: The top module name and the constraint reference have the same name: 'Zynq_Design_UART_V1_9_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: g:/Xilinx/Projects/Desktop/AXI_4_Lite_Slave/AXI_4_Lite_Slave.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_UART_V1_9_0_0/src/TOP_BD_ooc.xdc

# XDC: g:/Xilinx/Projects/Desktop/AXI_4_Lite_Slave/AXI_4_Lite_Slave.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_UART_V1_9_0_0/src/TOP_BD_fifo_generator_0_0/TOP_BD_fifo_generator_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TOP_BD_fifo_generator_0_0 || ORIG_REF_NAME==TOP_BD_fifo_generator_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: g:/Xilinx/Projects/Desktop/AXI_4_Lite_Slave/AXI_4_Lite_Slave.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_UART_V1_9_0_0/src/TOP_BD_fifo_generator_0_0/TOP_BD_fifo_generator_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TOP_BD_fifo_generator_0_0 || ORIG_REF_NAME==TOP_BD_fifo_generator_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: g:/Xilinx/Projects/Desktop/AXI_4_Lite_Slave/AXI_4_Lite_Slave.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_UART_V1_9_0_0/src/TOP_BD_fifo_generator_0_1/TOP_BD_fifo_generator_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TOP_BD_fifo_generator_0_1 || ORIG_REF_NAME==TOP_BD_fifo_generator_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: g:/Xilinx/Projects/Desktop/AXI_4_Lite_Slave/AXI_4_Lite_Slave.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_UART_V1_9_0_0/src/TOP_BD_fifo_generator_0_1/TOP_BD_fifo_generator_0_1_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TOP_BD_fifo_generator_0_1 || ORIG_REF_NAME==TOP_BD_fifo_generator_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
