@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sat May 15 15:54:42 -0400 2021
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim Zynq_Design_wrapper_behav -key {Behavioral:sim_1:Functional:Zynq_Design_wrapper} -tclbatch Zynq_Design_wrapper.tcl -protoinst "protoinst_files/TOP_BD.protoinst" -protoinst "protoinst_files/bd_8632.protoinst" -protoinst "protoinst_files/Zynq_Design.protoinst" -view G:/Xilinx/Projects/Desktop/AXI_4_Lite_Slave/Zynq_Design_wrapper_behav.wcfg -log simulate.log"
call xsim  Zynq_Design_wrapper_behav -key {Behavioral:sim_1:Functional:Zynq_Design_wrapper} -tclbatch Zynq_Design_wrapper.tcl -protoinst "protoinst_files/TOP_BD.protoinst" -protoinst "protoinst_files/bd_8632.protoinst" -protoinst "protoinst_files/Zynq_Design.protoinst" -view G:/Xilinx/Projects/Desktop/AXI_4_Lite_Slave/Zynq_Design_wrapper_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
