# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: g:/Xilinx/Projects/Desktop/ZyboBaseProject/ZyboBaseProject.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_auto_pc_0/Zynq_Design_auto_pc_0.xci
# IP: The module: 'Zynq_Design_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/Xilinx/Projects/Desktop/ZyboBaseProject/ZyboBaseProject.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_auto_pc_0/Zynq_Design_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Zynq_Design_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: g:/Xilinx/Projects/Desktop/ZyboBaseProject/ZyboBaseProject.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_auto_pc_0/Zynq_Design_auto_pc_0.xci
# IP: The module: 'Zynq_Design_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/Xilinx/Projects/Desktop/ZyboBaseProject/ZyboBaseProject.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_auto_pc_0/Zynq_Design_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Zynq_Design_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
