# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: G:/Xilinx/Projects/Desktop/AXI_4_Lite_Slave/AXI_4_Lite_Slave.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_rst_ps7_0_50M_0/Zynq_Design_rst_ps7_0_50M_0.xci
# IP: The module: 'Zynq_Design_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/Xilinx/Projects/Desktop/AXI_4_Lite_Slave/AXI_4_Lite_Slave.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_rst_ps7_0_50M_0/Zynq_Design_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Zynq_Design_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: g:/Xilinx/Projects/Desktop/AXI_4_Lite_Slave/AXI_4_Lite_Slave.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_rst_ps7_0_50M_0/Zynq_Design_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Zynq_Design_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: G:/Xilinx/Projects/Desktop/AXI_4_Lite_Slave/AXI_4_Lite_Slave.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_rst_ps7_0_50M_0/Zynq_Design_rst_ps7_0_50M_0.xci
# IP: The module: 'Zynq_Design_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/Xilinx/Projects/Desktop/AXI_4_Lite_Slave/AXI_4_Lite_Slave.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_rst_ps7_0_50M_0/Zynq_Design_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Zynq_Design_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: g:/Xilinx/Projects/Desktop/AXI_4_Lite_Slave/AXI_4_Lite_Slave.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_rst_ps7_0_50M_0/Zynq_Design_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Zynq_Design_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
