# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: G:/Xilinx/Projects/Desktop/AXI_4_Lite_Slave/AXI_4_Lite_Slave.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_system_ila_0_0/Zynq_Design_system_ila_0_0.xci
# IP: The module: 'Zynq_Design_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: g:/Xilinx/Projects/Desktop/AXI_4_Lite_Slave/AXI_4_Lite_Slave.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_system_ila_0_0/bd_0/bd_8632.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_8632 || ORIG_REF_NAME==bd_8632} -quiet] -quiet

# IP: g:/Xilinx/Projects/Desktop/AXI_4_Lite_Slave/AXI_4_Lite_Slave.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_system_ila_0_0/bd_0/ip/ip_0/bd_8632_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_8632_ila_lib_0 || ORIG_REF_NAME==bd_8632_ila_lib_0} -quiet] -quiet

# IP: g:/Xilinx/Projects/Desktop/AXI_4_Lite_Slave/AXI_4_Lite_Slave.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_system_ila_0_0/bd_0/ip/ip_1/bd_8632_g_inst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_8632_g_inst_0 || ORIG_REF_NAME==bd_8632_g_inst_0} -quiet] -quiet

# IP: g:/Xilinx/Projects/Desktop/AXI_4_Lite_Slave/AXI_4_Lite_Slave.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_system_ila_0_0/bd_0/ip/ip_2/bd_8632_slot_0_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_8632_slot_0_aw_0 || ORIG_REF_NAME==bd_8632_slot_0_aw_0} -quiet] -quiet

# IP: g:/Xilinx/Projects/Desktop/AXI_4_Lite_Slave/AXI_4_Lite_Slave.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_system_ila_0_0/bd_0/ip/ip_3/bd_8632_slot_0_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_8632_slot_0_w_0 || ORIG_REF_NAME==bd_8632_slot_0_w_0} -quiet] -quiet

# IP: g:/Xilinx/Projects/Desktop/AXI_4_Lite_Slave/AXI_4_Lite_Slave.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_system_ila_0_0/bd_0/ip/ip_4/bd_8632_slot_0_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_8632_slot_0_b_0 || ORIG_REF_NAME==bd_8632_slot_0_b_0} -quiet] -quiet

# IP: g:/Xilinx/Projects/Desktop/AXI_4_Lite_Slave/AXI_4_Lite_Slave.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_system_ila_0_0/bd_0/ip/ip_5/bd_8632_slot_0_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_8632_slot_0_ar_0 || ORIG_REF_NAME==bd_8632_slot_0_ar_0} -quiet] -quiet

# IP: g:/Xilinx/Projects/Desktop/AXI_4_Lite_Slave/AXI_4_Lite_Slave.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_system_ila_0_0/bd_0/ip/ip_6/bd_8632_slot_0_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_8632_slot_0_r_0 || ORIG_REF_NAME==bd_8632_slot_0_r_0} -quiet] -quiet

# XDC: g:/Xilinx/Projects/Desktop/AXI_4_Lite_Slave/AXI_4_Lite_Slave.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_8632_ila_lib_0 || ORIG_REF_NAME==bd_8632_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: g:/Xilinx/Projects/Desktop/AXI_4_Lite_Slave/AXI_4_Lite_Slave.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_8632_ila_lib_0 || ORIG_REF_NAME==bd_8632_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: g:/Xilinx/Projects/Desktop/AXI_4_Lite_Slave/AXI_4_Lite_Slave.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_system_ila_0_0/bd_0/ip/ip_0/bd_8632_ila_lib_0_ooc.xdc

# XDC: g:/Xilinx/Projects/Desktop/AXI_4_Lite_Slave/AXI_4_Lite_Slave.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_system_ila_0_0/bd_0/bd_8632_ooc.xdc

# IP: G:/Xilinx/Projects/Desktop/AXI_4_Lite_Slave/AXI_4_Lite_Slave.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_system_ila_0_0/Zynq_Design_system_ila_0_0.xci
# IP: The module: 'Zynq_Design_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: g:/Xilinx/Projects/Desktop/AXI_4_Lite_Slave/AXI_4_Lite_Slave.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_system_ila_0_0/bd_0/bd_8632.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_8632 || ORIG_REF_NAME==bd_8632} -quiet] -quiet

# IP: g:/Xilinx/Projects/Desktop/AXI_4_Lite_Slave/AXI_4_Lite_Slave.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_system_ila_0_0/bd_0/ip/ip_0/bd_8632_ila_lib_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_8632_ila_lib_0 || ORIG_REF_NAME==bd_8632_ila_lib_0} -quiet] -quiet

# IP: g:/Xilinx/Projects/Desktop/AXI_4_Lite_Slave/AXI_4_Lite_Slave.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_system_ila_0_0/bd_0/ip/ip_1/bd_8632_g_inst_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_8632_g_inst_0 || ORIG_REF_NAME==bd_8632_g_inst_0} -quiet] -quiet

# IP: g:/Xilinx/Projects/Desktop/AXI_4_Lite_Slave/AXI_4_Lite_Slave.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_system_ila_0_0/bd_0/ip/ip_2/bd_8632_slot_0_aw_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_8632_slot_0_aw_0 || ORIG_REF_NAME==bd_8632_slot_0_aw_0} -quiet] -quiet

# IP: g:/Xilinx/Projects/Desktop/AXI_4_Lite_Slave/AXI_4_Lite_Slave.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_system_ila_0_0/bd_0/ip/ip_3/bd_8632_slot_0_w_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_8632_slot_0_w_0 || ORIG_REF_NAME==bd_8632_slot_0_w_0} -quiet] -quiet

# IP: g:/Xilinx/Projects/Desktop/AXI_4_Lite_Slave/AXI_4_Lite_Slave.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_system_ila_0_0/bd_0/ip/ip_4/bd_8632_slot_0_b_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_8632_slot_0_b_0 || ORIG_REF_NAME==bd_8632_slot_0_b_0} -quiet] -quiet

# IP: g:/Xilinx/Projects/Desktop/AXI_4_Lite_Slave/AXI_4_Lite_Slave.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_system_ila_0_0/bd_0/ip/ip_5/bd_8632_slot_0_ar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_8632_slot_0_ar_0 || ORIG_REF_NAME==bd_8632_slot_0_ar_0} -quiet] -quiet

# IP: g:/Xilinx/Projects/Desktop/AXI_4_Lite_Slave/AXI_4_Lite_Slave.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_system_ila_0_0/bd_0/ip/ip_6/bd_8632_slot_0_r_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_8632_slot_0_r_0 || ORIG_REF_NAME==bd_8632_slot_0_r_0} -quiet] -quiet

# XDC: g:/Xilinx/Projects/Desktop/AXI_4_Lite_Slave/AXI_4_Lite_Slave.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_8632_ila_lib_0 || ORIG_REF_NAME==bd_8632_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: g:/Xilinx/Projects/Desktop/AXI_4_Lite_Slave/AXI_4_Lite_Slave.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_8632_ila_lib_0 || ORIG_REF_NAME==bd_8632_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: g:/Xilinx/Projects/Desktop/AXI_4_Lite_Slave/AXI_4_Lite_Slave.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_system_ila_0_0/bd_0/ip/ip_0/bd_8632_ila_lib_0_ooc.xdc

# XDC: g:/Xilinx/Projects/Desktop/AXI_4_Lite_Slave/AXI_4_Lite_Slave.srcs/sources_1/bd/Zynq_Design/ip/Zynq_Design_system_ila_0_0/bd_0/bd_8632_ooc.xdc
